In [2]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [5]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [6]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], errors='ignore', inplace=True)

In [15]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)

In [16]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

In [17]:
X = df.drop(columns=['Exited'])
y = df['Exited'].values
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [19]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

In [28]:
model = Sequential()
model.add(Dense(11,activation = 'relu',input_dim = 11))
model.add(Dense(11,activation = 'relu'))
model.add(Dense(1,activation = 'sigmoid')) 
#this model contains 11 input nodes then 2 hidden layer with 11 nodes each and 1 output layer with 1 node.

c:\Users\Asus\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [29]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.compile(loss='binary_crossentropy',optimizer = 'adam',metrics=['accuracy'])
model.fit(X_train_trf,y_train,epochs=100,batch_size=50,verbose=1,validation_split=0.2)

Epoch 1/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8622 - loss: 0.3215 - val_accuracy: 0.8637 - val_loss: 0.3355
Epoch 2/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8662 - loss: 0.3207 - val_accuracy: 0.8606 - val_loss: 0.3364
Epoch 3/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8662 - loss: 0.3203 - val_accuracy: 0.8637 - val_loss: 0.3375
Epoch 4/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8653 - loss: 0.3205 - val_accuracy: 0.8612 - val_loss: 0.3376
Epoch 5/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8661 - loss: 0.3200 - val_accuracy: 0.8625 - val_loss: 0.3381
Epoch 6/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8658 - loss: 0.3201 - val_accuracy: 0.8619 - val_loss: 0.3392
Epoch 7/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8664 - loss: 0.3198 - val_accuracy: 0.8606 - val_loss: 0.3395
Epoch 8/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8673 - loss: 0.3197 - val_accuracy: 0.8612 - val_loss: 0.3401
Epoch 9/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8658 - loss: 0.3198 - val_accuracy: 0.8625 - val_loss: 0.3413
Epoch 10/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8675 - loss: 0.3196 - val_accuracy: 0.8619 - val_loss: 0.3400
Epoch 11/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8689 - loss: 0.3196 - val_accuracy: 0.8600 - val_loss: 0.3410
Epoch 12/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8680 - loss: 0.3194 - val_accuracy: 0.8600 - val_loss: 0.3429
Epoch 13/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8677 - loss: 0.3196 - val_accuracy: 0.8619 - val_loss: 0.3416
Epoch 14/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8678 - loss: 0.3194 - val_accuracy: 0.8625 - val_loss: 0.3422
Epoch 15/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8687 - loss: 0.3196 - val_accuracy: 0.8625 - val_loss: 0.3418
Epoch 16/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8661 - loss: 0.3192 - val_accuracy: 0.8619 - val_loss: 0.3421
Epoch 17/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8686 - loss: 0.3190 - val_accuracy: 0.8625 - val_loss: 0.3424
Epoch 18/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8691 - loss: 0.3191 - val_accuracy: 0.8612 - val_loss: 0.3429
Epoch 19/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8673 - loss: 0.3185 - val_accuracy: 0.8631 - val_loss: 0.3450
Epoch 20/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8681 - loss: 0.3190 - val_accuracy: 0.8619 - val_loss: 0.3436
Epoch 21/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8683 - loss: 0.3189 - val_accuracy: 0.8612 - val_loss: 0.3441
Epoch 22/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8694 - loss: 0.3187 - val_accuracy: 0.8606 - val_loss: 0.3441
Epoch 23/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8675 - loss: 0.3184 - val_accuracy: 0.8619 - val_loss: 0.3444
Epoch 24/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8684 - loss: 0.3185 - val_accuracy: 0.8619 - val_loss: 0.3442
Epoch 25/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8678 - loss: 0.3182 - val_accuracy: 0.8631 - val_loss: 0.3446
Epoch 26/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8702 - loss: 0.3183 - val_accuracy: 0.8612 - val_loss: 0.3440
Epoch 27/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8683 - loss: 0.3184 - val_accuracy: 0.8606 - val_loss: 0.3444
Epoch 28/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8681 - loss: 0.3182 - val_accuracy: 0.8619 - val_loss: 0.3450
Epoch 29/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8684 - loss: 0.3180 - val_accuracy: 0.8625 - val_loss: 0.3445
Epoch 30/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8692 - loss: 0.3181 - val_accuracy: 0.8600 - val_loss: 0.3445
Epoch 31/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8683 - loss: 0.3179 - val_accuracy: 0.8631 - val_loss: 0.3446
Epoch 32/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8691 - loss: 0.3177 - val_accuracy: 0.8594 - val_loss: 0.3454
Epoch 33/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8695 - loss: 0.3176 - val_accuracy: 0.8606 - val_loss: 0.3444
Epoch 34/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8694 - loss: 0.3177 - val_accuracy: 0.8606 - val_loss: 0.3444
Epoch 35/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8702 - loss: 0.3176 - val_accuracy: 0.8612 - val_loss: 0.3477
Epoch 36/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8684 - loss: 0.3176 - val_accuracy: 0.8644 - val_loss: 0.3445
Epoch 37/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8698 - loss: 0.3173 - val_accuracy: 0.8606 - val_loss: 0.3466
Epoch 38/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8689 - loss: 0.3176 - val_accuracy: 0.8619 - val_loss: 0.3454
Epoch 39/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8678 - loss: 0.3172 - val_accuracy: 0.8594 - val_loss: 0.3455
Epoch 40/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8700 - loss: 0.3175 - val_accuracy: 0.8619 - val_loss: 0.3460
Epoch 41/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8698 - loss: 0.3175 - val_accuracy: 0.8606 - val_loss: 0.3459
Epoch 42/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8691 - loss: 0.3171 - val_accuracy: 0.8600 - val_loss: 0.3458
Epoch 43/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8694 - loss: 0.3171 - val_accuracy: 0.8594 - val_loss: 0.3486
Epoch 44/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8705 - loss: 0.3180 - val_accuracy: 0.8619 - val_loss: 0.3465
Epoch 45/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8686 - loss: 0.3175 - val_accuracy: 0.8625 - val_loss: 0.3468
Epoch 46/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8708 - loss: 0.3174 - val_accuracy: 0.8625 - val_loss: 0.3464
Epoch 47/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8689 - loss: 0.3175 - val_accuracy: 0.8594 - val_loss: 0.3485
Epoch 48/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8705 - loss: 0.3170 - val_accuracy: 0.8594 - val_loss: 0.3465
Epoch 49/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8708 - loss: 0.3171 - val_accuracy: 0.8625 - val_loss: 0.3468
Epoch 50/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8706 - loss: 0.3170 - val_accuracy: 0.8600 - val_loss: 0.3475
Epoch 51/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8700 - loss: 0.3170 - val_accuracy: 0.8581 - val_loss: 0.3468
Epoch 52/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8691 - loss: 0.3170 - val_accuracy: 0.8600 - val_loss: 0.3471
Epoch 53/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8695 - loss: 0.3168 - val_accuracy: 0.8612 - val_loss: 0.3474
Epoch 54/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8689 - loss: 0.3172 - val_accuracy: 0.8606 - val_loss: 0.3470
Epoch 55/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8709 - loss: 0.3169 - val_accuracy: 0.8619 - val_loss: 0.3472
Epoch 56/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8702 - loss: 0.3167 - val_accuracy: 0.8606 - val_loss: 0.3468
Epoch 57/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8706 - loss: 0.3169 - val_accuracy: 0.8606 - val_loss: 0.3478
Epoch 58/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8700 - loss: 0.3166 - val_accuracy: 0.8600 - val_loss: 0.3475
Epoch 59/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8705 - loss: 0.3166 - val_accuracy: 0.8600 - val_loss: 0.3491
Epoch 60/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8706 - loss: 0.3165 - val_accuracy: 0.8606 - val_loss: 0.3470
Epoch 61/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8703 - loss: 0.3167 - val_accuracy: 0.8600 - val_loss: 0.3477
Epoch 62/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8697 - loss: 0.3165 - val_accuracy: 0.8594 - val_loss: 0.3478
Epoch 63/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8708 - loss: 0.3166 - val_accuracy: 0.8606 - val_loss: 0.3474
Epoch 64/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8684 - loss: 0.3167 - val_accuracy: 0.8606 - val_loss: 0.3485
Epoch 65/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8700 - loss: 0.3161 - val_accuracy: 0.8606 - val_loss: 0.3475
Epoch 66/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8697 - loss: 0.3167 - val_accuracy: 0.8600 - val_loss: 0.3487
Epoch 67/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8706 - loss: 0.3165 - val_accuracy: 0.8600 - val_loss: 0.3491
Epoch 68/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8705 - loss: 0.3165 - val_accuracy: 0.8581 - val_loss: 0.3485
Epoch 69/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8687 - loss: 0.3162 - val_accuracy: 0.8600 - val_loss: 0.3481
Epoch 70/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8703 - loss: 0.3161 - val_accuracy: 0.8600 - val_loss: 0.3489
Epoch 71/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8703 - loss: 0.3160 - val_accuracy: 0.8587 - val_loss: 0.3484
Epoch 72/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8697 - loss: 0.3162 - val_accuracy: 0.8587 - val_loss: 0.3485
Epoch 73/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8712 - loss: 0.3158 - val_accuracy: 0.8612 - val_loss: 0.3505
Epoch 74/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8703 - loss: 0.3160 - val_accuracy: 0.8594 - val_loss: 0.3486
Epoch 75/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8712 - loss: 0.3160 - val_accuracy: 0.8594 - val_loss: 0.3493
Epoch 76/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8694 - loss: 0.3160 - val_accuracy: 0.8606 - val_loss: 0.3491
Epoch 77/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8714 - loss: 0.3158 - val_accuracy: 0.8594 - val_loss: 0.3491
Epoch 78/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8714 - loss: 0.3160 - val_accuracy: 0.8587 - val_loss: 0.3486
Epoch 79/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8727 - loss: 0.3157 - val_accuracy: 0.8619 - val_loss: 0.3504
Epoch 80/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8700 - loss: 0.3159 - val_accuracy: 0.8612 - val_loss: 0.3497
Epoch 81/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8712 - loss: 0.3157 - val_accuracy: 0.8587 - val_loss: 0.3490
Epoch 82/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8702 - loss: 0.3159 - val_accuracy: 0.8594 - val_loss: 0.3499
Epoch 83/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8711 - loss: 0.3158 - val_accuracy: 0.8606 - val_loss: 0.3490
Epoch 84/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8703 - loss: 0.3159 - val_accuracy: 0.8600 - val_loss: 0.3496
Epoch 85/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8723 - loss: 0.3157 - val_accuracy: 0.8594 - val_loss: 0.3494
Epoch 86/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8708 - loss: 0.3153 - val_accuracy: 0.8600 - val_loss: 0.3489
Epoch 87/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8720 - loss: 0.3156 - val_accuracy: 0.8581 - val_loss: 0.3491
Epoch 88/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8705 - loss: 0.3154 - val_accuracy: 0.8600 - val_loss: 0.3504
Epoch 89/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8709 - loss: 0.3152 - val_accuracy: 0.8594 - val_loss: 0.3493
Epoch 90/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8711 - loss: 0.3156 - val_accuracy: 0.8587 - val_loss: 0.3494
Epoch 91/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8717 - loss: 0.3152 - val_accuracy: 0.8600 - val_loss: 0.3497
Epoch 92/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8717 - loss: 0.3149 - val_accuracy: 0.8587 - val_loss: 0.3500
Epoch 93/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8709 - loss: 0.3152 - val_accuracy: 0.8581 - val_loss: 0.3496
Epoch 94/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8720 - loss: 0.3150 - val_accuracy: 0.8581 - val_loss: 0.3502
Epoch 95/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8714 - loss: 0.3147 - val_accuracy: 0.8600 - val_loss: 0.3507
Epoch 96/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8708 - loss: 0.3150 - val_accuracy: 0.8587 - val_loss: 0.3495
Epoch 97/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8703 - loss: 0.3148 - val_accuracy: 0.8581 - val_loss: 0.3497
Epoch 98/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8700 - loss: 0.3144 - val_accuracy: 0.8581 - val_loss: 0.3498
Epoch 99/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8714 - loss: 0.3148 - val_accuracy: 0.8606 - val_loss: 0.3505
Epoch 100/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8712 - loss: 0.3146 - val_accuracy: 0.8594 - val_loss: 0.3506

In [31]:
model.layers[1].get_weights()

[array([[ 0.5205097 ,  0.29655275,  0.35012385,  0.3117208 , -0.5879702 ,
         -0.7282558 ,  0.25988132,  0.47361118, -0.08940475, -0.46314037,
          0.49987975],
        [ 0.32085654,  0.49566886, -0.09161709,  0.5861871 , -0.14278536,
         -0.11577804,  0.39619434, -0.55935377, -0.12807003, -0.0926531 ,
          0.05137014],
        [-0.12712964, -0.17203234, -0.11614206,  0.35038716,  0.45824885,
         -0.12718798, -0.55284375, -0.12278502,  0.47558755, -0.25571436,
          0.6249925 ],
        [ 0.45874977,  0.04514493, -0.5673766 ,  0.49453074,  0.01279711,
         -0.6954173 ,  0.15001628, -0.5309285 ,  0.33237663, -0.943267  ,
         -0.11247575],
        [-0.8722515 ,  0.5523954 ,  0.57726896, -0.90939754, -0.44542667,
          0.6873693 ,  0.33274907,  0.06624034,  0.17764728, -0.8497174 ,
         -0.47114894],
        [ 0.26892638,  0.31328946, -0.13587585, -0.06536975,  0.12264388,
         -0.10817824, -1.1230652 ,  0.651785  ,  0.18236448,  0.47183043,
         -0.1971399 ],
        [ 0.21982259, -0.575725  , -0.29869655, -0.22481151, -0.00949727,
         -0.11849162, -0.27057046,  0.8451523 , -0.78863156, -0.05682477,
         -0.12225151],
        [-0.07593329,  0.343975  ,  0.4226312 ,  0.06815041,  0.51470244,
          0.5418933 , -0.14115135, -0.39827865,  0.67278033,  0.24214393,
         -0.19520193],
        [-0.20891309, -0.7274199 ,  0.12139924, -0.76530236, -0.68751895,
          0.3899047 ,  1.4546278 ,  0.87236774, -0.8284171 , -0.13438162,
         -0.17556123],
        [ 0.08728483, -0.06579837, -0.803172  ,  0.4264035 , -0.55629045,
         -1.0195671 , -0.29854983, -0.5628266 ,  0.4024999 ,  0.03853207,
          0.24511148],
        [-0.00364051, -0.1688333 ,  0.3219662 , -0.06204115,  0.08679721,
          0.67572   , -0.0164438 , -0.8251562 ,  0.49065104, -0.4483313 ,
          0.20166706]], dtype=float32),
 array([ 0.47223967,  0.22083493, -0.0037559 ,  0.4406846 , -0.02757201,
        -0.17425017, -0.52058655,  0.37605804,  0.19166857, -0.04460586,
         0.75768244], dtype=float32)]

In [32]:
y_log = model.predict(X_test_trf)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [35]:
y_pred = np.where(y_log>0.5,1,0)

from sklearn.metrics import accuracy_score 
accuracy_score(y_test,y_pred)

0.8595